#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S2,     HTIRS2,         sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorL1,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorL2,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorA1,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorA2,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorR1,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorR2,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

const bool DEBUG_ENABLED = true;

void initializeRobot()
{
  return;
}

task main()
{
  initializeRobot();
	if (DEBUG_ENABLED) {
		writeDebugStreamLine("Robot initiation complete, now waiting for start...");
		writeDebugStream("External battery: ");
		if(externalBattery == -1) {
			writeDebugStreamLine("nonexistent");
		} else {
			writeDebugStreamLine("%f", (externalBatteryAvg / 1000));
		}

		writeDebugStream("Internal battery: %f", (nAvgBatteryLevel / 1000));
	}

  waitForStart();   // wait for start of tele-op phase

  while (true)
  {
		if (abs(joystick.joy1_x1) != 0) {
	  	motor[motorL1] = motor[motorL2] = joystick.joy1_x1;
	  	if(DEBUG_ENABLED) {
	  		writeDebugStreamLine("[Left Motor] - %d", joystick.joy1_x1);
	  	}
		}
		if (abs(joystick.joy1_x2) != 0) {
			motor[motorR1] = motor[motorR2] = joystick.joy1_x2;
			if (DEBUG_ENABLED) {
				writeDebugStreamLine("[Right Motor] - %d", joystick.joy1_x2);
			}
		}
  }





}
